replicaCount: 2

image:
  repository: oink12268/usonly
  tag: "43"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: usonly.duckdns.org
  tlsSecretName: usonly-tls

mysql:
  host: mysql
  port: 3306
  database: usonly
  username: root

gemini:
  secretName: gemini-secret
  secretKey: api-key
  
javaOpts: "-Xms48m -Xmx128m -XX:MaxMetaspaceSize=150m -XX:+UseSerialGC"
