replicaCount: 1

image:
  repository: oink12268/usonly
  tag: "10"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30080

mysql:
  host: mysql
  port: 3306
  database: usonly
  username: root
