replicaCount: 1

image:
  repository: oink12268/usonly
  tag: "24"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: usonly.duckdns.org
  tlsSecretName: usonly-tls

mysql:
  host: mysql
  port: 3306
  database: usonly
  username: root
