apiVersion: apps/v1
kind: Deployment
metadata:
  name: usonly-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: usonly
  template:
    metadata:
      labels:
        app: usonly
    spec:
      containers:
        - name: usonly
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.mysql.username }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.mysql.password }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
