apiVersion: v1
kind: Service
metadata:
  name: usonly-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: usonly
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
